#!/usr/bin/env python3

import asyncio
import time

# Import MAVSDK
from mavsdk import System

#The following program is supposed to, in order:
#make the drone take off to 100 ft, 
#hover for 10 seconds
#land the drone

# Async Python - run the main code body
# Note that since most MAVSDK actions run async,
# they need to be run using the await keyword
async def run():
  drone = System()
  await drone.connect(system_address="udp://:14540")

  print("Waiting for drone...")
  async for state in drone.core.connection_state():
    # This will basically run every time a drone connects
    if state.is_connected:
      #print(f"Drone discovered with UUID: {state.uuid}")
      print(f"Drone discovered!")
      break


  print("-- Arming")
  await drone.action.arm()

  print("-- Taking off")
  # https://mavsdk.mavlink.io/develop/en/api_reference/classmavsdk_1_1_action.html#classmavsdk_1_1_action_1ace2188fe367b3bb10b17b89c88d1f952 - may help to read
  await drone.action.set_takeoff_altitude(10)
  print (await drone.action.get_takeoff_altitude())
  await drone.action.takeoff()
  #await drone.action.hold()
  #async for position in drone.telemetry.position():
    #if position.relative_altitude_m >= 10:
      #await asyncio.sleep(10)
      #print (f"Commencing sleep...")
      #print("-- Landing")
      #await drone.action.land()
  async for position in drone.telemetry.position():
    if position.relative_altitude_m == 10:
      print(f"Drone has reached maximum altitude!")
      await asyncio.sleep(10)
      #print(f"1")
      #await asyncio.sleep(1)
      #print(f"2")
      #await asyncio.sleep(1)
      #print(f"3")
      #await asyncio.sleep(1)
      #print(f"4")
      #await asyncio.sleep(1)
      #print(f"5")
      break

    #await asyncio.sleep(20)
  #print (await drone.action.get_takeoff_altitude())
  #await asyncio.sleep(10)
  #async for position in drone.telemetry.position():
    #print(position)
  print("-- Landing")
  await drone.action.land()


loop = asyncio.get_event_loop()
loop.run_until_complete(run())